services:
  - type: web
    name: marketplace-backend
    runtime: node
    repo: https://github.com/superprince1/Marketplace-
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
